FROM golang:1.23 AS builder

WORKDIR /app

COPY . .

RUN GOOS=linux GOARCH=amd64 CGO_ENABLED=0 go build -o webapi ./cmd/webapi

FROM alpine:3

WORKDIR /root/

COPY --from=builder /app/webapi .

RUN chmod +x ./webapi

EXPOSE 8080

CMD ["./webapi"]
