# Stage 1: build
FROM golang:1.23 AS builder

WORKDIR /src
COPY . .

RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o webapi ./cmd/webapi


# Stage 2: runtime
FROM alpine:3

# cartella "neutra" (NON /root)
WORKDIR /app

# copia binario
COPY --from=builder /src/webapi ./webapi

# permessi: eseguibile + leggibile
RUN chmod 755 ./webapi

EXPOSE 8080

CMD ["./webapi"]
